export const quickStartStyles = {
  header: 'mb-6 sm:mb-8',
  title: 'text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3 sm:mb-4',
  subtitle: 'text-base sm:text-lg text-white/60 mb-4 sm:mb-6',
  section: 'mb-6 sm:mb-8',
  sectionTitle: 'text-xl sm:text-2xl font-bold text-white mb-3 sm:mb-4',
  card: 'bg-white/5 border border-white/10 rounded-lg sm:rounded-xl p-4 sm:p-6 mb-3 sm:mb-4',
  cardTitle: 'text-lg sm:text-xl font-semibold text-white mb-2 sm:mb-3',
  list: 'space-y-2 sm:space-y-3 text-sm sm:text-base text-white/80',
  listItem: 'flex items-start gap-2 sm:gap-3',
  bullet: 'text-primary mt-1 shrink-0',
  number: 'bg-primary text-black font-bold rounded-full w-7 h-7 sm:w-8 sm:h-8 flex items-center justify-center shrink-0 text-sm',
  code: 'bg-white/10 px-2 py-1 rounded text-xs sm:text-sm text-primary font-mono',
  note: 'bg-blue-500/10 border border-blue-500/30 rounded-lg p-3 sm:p-4 text-sm sm:text-base text-blue-200',
};
